// CAPCUT SIGNUP VIA API (FAST mode) — call fetch right inside the page.
// Port of capcut_api.py; every measured-behavior note from the Python file is
// kept (translated) — it is the real documentation of these endpoints.
//
// Why a browser is still needed: the two decisive requests (`send_code`,
// `register_verify_login`) must carry `X-Bogus` / `X-Gnarly` / `msToken` —
// ByteDance's anti-bot signature, generated by obfuscated JS served from
// `mssdk-sg.capcutapi.com`. It could NOT be reversed: 462 md5/sha1/sha256
// combinations were tried for age_gate's `sign` alone — no match.
//
// BUT one thing WAS measured: the SDK hooks the page's `fetch` AND
// `XMLHttpRequest` (neither prints `[native code]` any more). So a plain
// in-page fetch makes the browser itself inject the signature into the query
// string. Verified by real experiment: calling `send_code` with nothing added,
// the outgoing URL still carried `X-Bogus=...&X-Gnarly=...&msToken=...` and
// returned `email_ticket`.
//
// => FAST MODE = keep Chrome (so the SDK signs) + drop all the clicking and
//    typing across the 9 screens, replaced by 4 fetch calls.
//
//   *** NEVER add X-Bogus / X-Gnarly / msToken / device-time / sign headers ***
//   *** by hand. The hooked fetch adds them itself; hand-adding them BREAKS  ***
//   *** the signature (measured).                                           ***
//
// Parameter encoding: email/password/code are NOT sent raw — each char is
// XORed with 0x05 then hexed (verified two-way against real netlog data).
//
// API chain (extracted from the netlog of one successful signup):
//     POST /passport/web/user/check_email_registered   -> is the email free?
//     POST /lv/v1/sc/age_gate/check_age_without_uid    -> old enough?
//     POST /passport/web/email/send_code/              -> send code, returns email_ticket
//     POST /passport/web/email/register_verify_login/  -> create account + session cookie

import { StopRequested, checkStop, waitForDomReady } from '../browser/browser.js';
import { randInt, sleep } from '../util/util.js';

// Fixed CapCut web parameters, copied verbatim from a real request.
const AID = 348188;
const SDK_VERSION = '2.1.10-tiktok';
// type=34 = the "sign up with email + password" flow (seen in BOTH send_code
// and register_verify_login in the netlog).
const EMAIL_TYPE = 34;

const LOGIN_HOST_DEFAULT = 'https://login-row.www.capcut.com';

// XOR each char with 0x05 then hex — verified two-way against real netlog
// data (email, password and the 6-digit code all round-tripped).
export function xorHex(text) {
  return [...text].map((c) => ((c.codePointAt(0) ^ 0x05).toString(16).padStart(2, '0'))).join('');
}

// Reverse decode — used when re-reading netlog to cross-check. Throws on
// invalid hex (same contract as Python's bytes.fromhex).
export function xorUnhex(hexs) {
  const pairs = String(hexs).match(/../g);
  if (!pairs) throw new TypeError(`xorUnhex: invalid hex: ${hexs}`);
  return pairs.map((h) => String.fromCharCode(parseInt(h, 16) ^ 0x05)).join('');
}

// ---------------------------------------------------------------------------
// Calling the API from inside the page
// ---------------------------------------------------------------------------

// Race page.evaluate against a hard timeout — parity with pychrome's
// Runtime.evaluate `_timeout=60` (playwright's evaluate has no per-call
// timeout). 60s, not 30s: with 10 worker threads the in-page call sometimes
// runs past 30s while a tab is busy (measured batch 00:55 2026-09-01: 7
// overruns across 48 accounts). Waiting longer costs nothing on an idle tab —
// it only costs time when the tab is busy, which is exactly when waiting is
// needed. (Duplicated in capcut-tasks.js on purpose: no shared contract slot.)
async function evalTimed(page, expr, timeoutMs = 60000) {
  const work = page.evaluate(expr);
  let timer = null;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => {
      const err = new Error(`page.evaluate timed out after ${timeoutMs}ms`);
      err.name = 'TimeoutException'; // same name pychrome raised, for log parity
      reject(err);
    }, timeoutMs);
  });
  try {
    return await Promise.race([work, timeout]);
  } finally {
    clearTimeout(timer);
    work.catch(() => {}); // swallow the losing promise's late rejection
  }
}

// Readiness probe: the signing SDK exposes `window.byted_acrawler` and has
// hooked `fetch` (so it is no longer the native function).
const SDK_READY_EXPR =
  "(()=>{try{return !!window.byted_acrawler && " +
  "!String(window.fetch).includes('[native code]')}" +
  "catch(e){return false}})()";

// In-page fetch with `credentials:'include'` so the session cookie is sent and
// received exactly like a real browser request.
// DO NOT add X-Bogus/X-Gnarly/msToken yourself: the SDK already hooked fetch
// and injects them into the query string; adding them by hand only breaks the
// signature. Response body is truncated to 800 chars for logging (as Python).
const JS_FORM_POST_FN = `(async (host, path, qs, body) => {
    const u = host + path + '?' + qs;
    try {
        const r = await (window.__nativeFetch || window.fetch)(u, {
            method: 'POST',
            credentials: 'include',
            headers: {'Content-Type': 'application/x-www-form-urlencoded'},
            body: body,
        });
        const t = await r.text();
        let j = null;
        try { j = JSON.parse(t); } catch (e) {}
        return {status: r.status, ok: r.ok, json: j, text: t.slice(0, 800)};
    } catch (e) {
        return {status: 0, ok: false, json: null, text: String(e)};
    }
})`;

// The /lv/v1/... APIs live on the same www.capcut.com origin and need the
// `device-time` + `sign` header pair. We do NOT compute `sign` (probing
// failed — see the 462-combination note) — but it was measured that the
// page's hooked fetch adds it by itself, exactly like X-Bogus. So this bare
// in-page JSON POST works; a Node-side fetch would NOT.
const JS_JSON_POST_FN = `(async (url, payload) => {
    try {
        const r = await (window.__nativeFetch || window.fetch)(url, {
            method: 'POST',
            credentials: 'include',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify(payload),
        });
        const t = await r.text();
        let j = null;
        try { j = JSON.parse(t); } catch (e) {}
        return {status: r.status, ok: r.ok, json: j, text: t.slice(0, 800)};
    } catch (e) {
        return {status: 0, ok: false, json: null, text: String(e)};
    }
})`;

// Shared query string of every /passport/web/... request.
function commonQs(locale = 'vi-VN') {
  return `aid=${AID}&account_sdk_source=web&sdk_version=${SDK_VERSION}&language=${locale}`;
}

// Marshal a form POST through the page (SDK signs it). Args are embedded as
// JSON literals — same technique as Python's json.dumps + %s substitution.
async function formPost(page, host, path, body, locale = 'vi-VN', timeoutMs = 60000) {
  const expr = `${JS_FORM_POST_FN}(${JSON.stringify(host)}, ${JSON.stringify(path)}, ` +
    `${JSON.stringify(commonQs(locale))}, ${JSON.stringify(body)})`;
  return evalTimed(page, expr, timeoutMs);
}

// Marshal a JSON POST through the page (SDK signs it).
async function jsonPost(page, url, payload, timeoutMs = 60000) {
  const expr = `${JS_JSON_POST_FN}(${JSON.stringify(url)}, ${JSON.stringify(payload)})`;
  return evalTimed(page, expr, timeoutMs);
}

// Human-readable error message from a passport response.
function msg(resp) {
  if (!resp) return 'no response';
  const j = resp.json || {};
  const d = j.data || {};
  const parts = [];
  if (d.description) parts.push(String(d.description));
  if (d.error_code) parts.push(`error_code=${d.error_code}`);
  if (j.message && j.message !== 'success') parts.push(String(j.message));
  if (!parts.length) parts.push(`HTTP ${resp.status} ${String(resp.text ?? '').slice(0, 160)}`);
  return parts.join(' | ');
}

// True when the passport response says success (HTTP ok + message == 'success').
function isSuccess(resp) {
  const j = (resp || {}).json || {};
  return Boolean(resp && resp.ok && j.message === 'success');
}

// Read an integer setting with a default (Python getattr(settings, k, d) +
// int()). NaN-safe: a hand-edited config falls back to the default instead of
// poisoning randInt with NaN.
function intSetting(value, fallback) {
  const n = Number.parseInt(value ?? fallback, 10);
  return Number.isFinite(n) ? n : fallback;
}

// ---------------------------------------------------------------------------
// Individual steps
// ---------------------------------------------------------------------------

// Open the login page and WAIT until the signing SDK has loaded — mandatory
// before any API call. Until then `fetch` is not hooked, requests go out
// unsigned and get rejected. Readiness = `window.byted_acrawler` (the signing
// SDK) exists AND `fetch` no longer contains '[native code]'.
export async function warmUp(page, { localePath = 'vi-vn', log = console.log, shouldStop = null } = {}) {
  checkStop(shouldStop);
  const url = `https://www.capcut.com/${localePath}/login`;
  log(`[>] Opening ${url} for the SDK to load its signature ...`);
  await page.goto(url, { timeout: 90000 }); // 90s: heavy first load through slower proxy exits (30s measured too tight)
  await waitForDomReady(page, { timeout: 25, settle: [0.5, 1.0] });

  const deadline = Date.now() + 30000;
  while (Date.now() < deadline) {
    checkStop(shouldStop);
    let ready = false;
    try {
      ready = await evalTimed(page, SDK_READY_EXPR);
    } catch (e) {
      // Python caught only RuntimeError here — pychrome's TimeoutException
      // ESCAPED warm_up (it is not a RuntimeError); keep that exact behavior:
      // rethrow our TimeoutException, swallow page-side JS errors.
      if (e && e.name === 'TimeoutException') throw e;
      ready = false;
    }
    if (ready) {
      log('    [ok] SDK ready (fetch is hooked).');
      return true;
    }
    await sleep(300);
  }
  log('    [!] 30s wait over, SDK has not hooked fetch yet — requests may go out unsigned.');
  return false;
}

// Early, cheap check: true if the email is NOT yet registered, null when the
// check itself failed. Rented mailboxes occasionally reuse an already-burned
// address; catching that early saves a wasted code-send.
export async function checkEmailFree(page, email, { host = LOGIN_HOST_DEFAULT, locale = 'vi-VN', log = console.log } = {}) {
  const body = `mix_mode=1&email=${xorHex(email)}&fixed_mix_mode=1`;
  const r = await formPost(page, host, '/passport/web/user/check_email_registered', body, locale);
  if (!isSuccess(r)) {
    log(`    [i] Could not check email (skipping): ${msg(r)}`);
    return null;
  }
  const d = (r.json || {}).data || {};
  return d.is_registered === 0;
}

// Pass the age gate; `birthday` is 'YYYY-MM-DD'. Not strictly required for
// account creation (register_verify_login takes its own `birthday`), but the
// real user flow calls it — keep it to behave like a human.
export async function checkAge(page, birthday, { log = console.log } = {}) {
  const r = await jsonPost(page,
    'https://www.capcut.com/lv/v1/sc/age_gate/check_age_without_uid',
    { birthday });
  const j = r.json || {};
  if (String(j.ret) === '0' && (j.data || {}).passed) return true;
  log(`    [i] age_gate did not confirm (continuing anyway): ${j.errmsg || String(r.text ?? '').slice(0, 120)}`);
  return false;
}

// Send the verification code to the mailbox. Returns `email_ticket` (possibly
// '') or null on failure. This is the FIRST request that requires the
// signature — if the SDK has not hooked fetch yet, it fails exactly here.
export async function sendCode(page, email, password, { host = LOGIN_HOST_DEFAULT, locale = 'vi-VN', log = console.log } = {}) {
  const body = `mix_mode=1&email=${xorHex(email)}&password=${xorHex(password)}&type=${EMAIL_TYPE}&fixed_mix_mode=1`;
  const r = await formPost(page, host, '/passport/web/email/send_code/', body, locale);
  if (!isSuccess(r)) {
    log(`    [!] send_code failed: ${msg(r)}`);
    return null;
  }
  const d = (r.json || {}).data || {};
  return d.email_ticket || '';
}

// Create the account. Returns the user object (contains user_id) or null.
// After this call the browser holds the session cookie -> treat as logged in.
// Note: a success with an EMPTY data object counts as failure, matching
// Python's dict truthiness (`if user:` is false for {}).
export async function register(page, email, password, code, birthday,
  { region = 'VN', host = LOGIN_HOST_DEFAULT, locale = 'vi-VN', log = console.log } = {}) {
  const body = `mix_mode=1&email=${xorHex(email)}&code=${xorHex(code)}&password=${xorHex(password)}&type=${EMAIL_TYPE}` +
    `&birthday=${birthday}&force_user_region=${region}` +
    '&biz_param=%7B%22invite_code%22%3A%22%22%7D&fixed_mix_mode=1'; // pre-encoded {"invite_code":""}
  const r = await formPost(page, host, '/passport/web/email/register_verify_login/', body, locale);
  if (!isSuccess(r)) {
    log(`    [!] register failed: ${msg(r)}`);
    return null;
  }
  return (r.json || {}).data || {};
}

// Rename the default workspace (`user123's space`) to `name`. Must fetch
// `workspace_id` first via get_user_workspaces. Optional: on failure the
// account still works, it just keeps the default name.
export async function renameWorkspace(page, name, { log = console.log } = {}) {
  const r = await jsonPost(page,
    'https://edit-api-sg.capcut.com/cc/v1/workspace/get_user_workspaces',
    { cursor: '0', count: 100, need_convert_workspace: true });
  const j = r.json || {};
  const infos = ((j.data || {}).workspace_infos) || [];
  if (!infos.length) {
    log(`    [i] Could not get workspace_id — keeping the default name (${j.errmsg || String(r.text ?? '').slice(0, 100)}).`);
    return false;
  }
  const wid = infos[0].workspace_id;
  const r2 = await jsonPost(page,
    'https://edit-api-sg.capcut.com/cc/v1/workspace/update_workspace_info',
    { workspace_id: wid, name, avatar_color: 'var(--lvv-color-common-purple-1)' });
  const j2 = r2.json || {};
  if (String(j2.ret) === '0') {
    log(`    [ok] Workspace name: ${name}`);
    return true;
  }
  log(`    [i] Could not rename workspace: ${j2.errmsg || String(r2.text ?? '').slice(0, 100)}`);
  return false;
}

// Skip the onboarding questionnaire (equivalent to pressing 'Skip').
export async function skipQuestionnaire(page, { log = console.log } = {}) {
  const r = await jsonPost(page,
    'https://edit-api-sg.capcut.com/lv/v1/persona/submit_questionnaire',
    { question_list: null });
  const j = r.json || {};
  if (String(j.ret) === '0') return true;
  log(`    [i] Could not skip the questionnaire: ${j.errmsg || String(r.text ?? '').slice(0, 100)}`);
  return false;
}

// ---------------------------------------------------------------------------
// Full flow
// ---------------------------------------------------------------------------

// Register ONE CapCut account purely via API (no UI clicks). Returns
// {ok: boolean, birthday: string|null} — Python returned the tuple
// (ok, birthday). `page` must be a tab with capcut.com already open.
// Python's (page, otp, order, ...) collapsed into the mailbox seam:
// mailbox.waitForCode({timeout, log, shouldStop}) -> 6-digit code | null
// (src/infra/mail.js contract). Python distinguished OKOTPDead (dead mailbox ->
// abort) from OKOTPError (transient); the own-domain IMAP reader has no
// "dead" state, so waitForCode simply returns null on a miss.
export async function signupViaApi(page, mailbox, email, password, settings,
  { log = console.log, shouldStop = null } = {}) {
  const localePath = settings.CAPCUT_LOCALE || 'vi-vn';
  // 'vi-vn' in the URL but 'vi-VN' in the API query string.
  const parts = localePath.split('-');
  const localeQ = parts.length === 2 ? `${parts[0]}-${parts[1].toUpperCase()}` : localePath;

  const yMin = intSetting(settings.BIRTH_YEAR_MIN, 1988);
  const yMax = intSetting(settings.BIRTH_YEAR_MAX, 2003);
  const year = randInt(Math.min(yMin, yMax), Math.max(yMin, yMax));
  const month = randInt(1, 12);
  const day = randInt(1, 28); // 1..28 stays valid for every month
  const birthdayApi = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  const birthdayOut = `${String(day).padStart(2, '0')}/${String(month).padStart(2, '0')}/${year}`;

  await warmUp(page, { localePath, log, shouldStop });
  checkStop(shouldStop);

  // Login host is region-dependent; /passport/web/region/ returns it, but the
  // real flow always landed on login-row for VN — use it directly, saves one
  // round-trip.
  const host = settings.CAPCUT_LOGIN_HOST || LOGIN_HOST_DEFAULT;

  log(`[>] API 1/4: checking email ${email}`);
  const free = await checkEmailFree(page, email, { host, locale: localeQ, log });
  if (free === false) {
    log('    [!] This email is ALREADY registered — dropping the account.');
    return { ok: false, birthday: null };
  }
  checkStop(shouldStop);

  log(`[>] API 2/4: age gate (${birthdayOut})`);
  await checkAge(page, birthdayApi, { log });
  checkStop(shouldStop);

  // Send the code: a first failure is usually a network hiccup or CapCut
  // rate-limiting — retrying is far cheaper than abandoning the whole
  // account (the mailbox is already rented).
  log('[>] API 3/4: sending the verification code');
  let ticket = null;
  for (let lan = 0; lan < 3; lan++) {
    ticket = await sendCode(page, email, password, { host, locale: localeQ, log });
    if (ticket !== null) break;
    if (lan < 2) {
      log(`    [i] code send failed on try ${lan + 1} — retrying in 3s`);
      await sleep(3000);
      checkStop(shouldStop);
    }
  }
  if (ticket === null) return { ok: false, birthday: null };
  log(`    [ok] Code sent (ticket: ${String(ticket).slice(0, 12)}...)`);

  const timeout = intSetting(settings.OTP_CODE_TIMEOUT, 300);

  // Wait for the code via the mailbox seam (replaces Python's cho_ma/otp).
  const waitCode = (secs) => mailbox.waitForCode({ timeout: secs, log, shouldStop });

  // Wait half the budget; if the mail has not arrived, RESEND the code once
  // and wait the rest. CapCut mail drops occasionally, and abandoning now
  // loses both the rented mailbox and the half-created account.
  const firstStretch = Math.max(60, Math.trunc(timeout / 2));
  log(`[i] Code sent — waiting for the email (up to ${firstStretch}s; CapCut mail to the catch-all often takes ~3-4 min, browser idles on the login page meanwhile) ...`);
  let code = await waitCode(firstStretch);
  checkStop(shouldStop);
  if (!code) {
    log(`    [i] No code after ${firstStretch}s — resending the code once`);
    const ticket2 = await sendCode(page, email, password, { host, locale: localeQ, log });
    if (ticket2 !== null) ticket = ticket2;
    code = await waitCode(timeout - firstStretch);
    checkStop(shouldStop);
  }
  if (!code) {
    log(`    [!] ${timeout}s elapsed and no code arrived.`);
    return { ok: false, birthday: null };
  }
  log(`    [ok] Verification code: ${code}`);

  // Create the account: one retry for transient errors. The 6-digit code
  // lives for a few minutes so it can be reused; a WRONG code fails both
  // times, costing nothing extra.
  log('[>] API 4/4: creating the account');
  let user = null;
  for (let lan = 0; lan < 2; lan++) {
    user = await register(page, email, password, code, birthdayApi, {
      region: settings.CAPCUT_REGION || 'VN',
      host,
      locale: localeQ,
      log,
    });
    if (user && Object.keys(user).length > 0) break; // Python dict truthiness: {} = failure
    if (lan === 0) {
      log('    [i] account creation failed — retrying in 3s');
      await sleep(3000);
      checkStop(shouldStop);
    }
  }
  if (!user || Object.keys(user).length === 0) return { ok: false, birthday: null };
  log(`    [ok] Created: user_id=${user.user_id_str || user.user_id} | ${user.screen_name || ''}`);

  // Post-steps (optional): rename workspace + skip questionnaire.
  //
  // DEFAULT OFF (API_DO_POST_STEPS=false). Really tried running them: these
  // two APIs (edit-api-sg.capcut.com) return "system busy" (ret 1014) and
  // "sign error" because they demand the `sign` + `device-time` headers.
  // Unlike the /passport/... group, which the page SDK signs automatically
  // for in-page fetches, the /cc/v1 and /lv/v1 groups sign at a different
  // layer, so a bare in-page fetch cannot reuse them.
  //
  // Consequence: accounts created in 'api' mode keep the default workspace
  // name. Need a random name? Set SIGNUP_MODE='ui'.
  if (settings.API_DO_POST_STEPS) {
    log('[>] Post-steps: renaming workspace & skipping the questionnaire');
    // Wrap the WHOLE post-step block: the account is already CREATED above
    // (user_id exists; the mailbox and verification code are already spent).
    // Post-steps are only cosmetic renaming — letting an error escape here
    // throws away a REAL account. Measured batch 00:55 2026-09-01: 5/48
    // accounts lost exactly this way — pychrome's TimeoutException (NOT a
    // RuntimeError, so every RuntimeError handler missed it) escaping
    // Runtime.evaluate while running 10 threads.
    try {
      // /my-space was removed by CapCut: returns 404 ("Goofy Deploy Page
      // Server"), measured 2026-08-31 — a dead page has no SDK, so every
      // later step would fail too. /my-edit is where the real app navigates.
      await page.goto('https://www.capcut.com/my-edit', { timeout: 90000 });
      await waitForDomReady(page, { timeout: 25, settle: [1.5, 2.5] });
      checkStop(shouldStop);
      // Lazy import mirrors Python's function-level `import gen` (and keeps
      // this optional path from loading gen.js at module import time).
      const { randomWorkspaceName } = await import('../util/gen.js');
      await renameWorkspace(page, randomWorkspaceName(), { log });
      await skipQuestionnaire(page, { log });
    } catch (e) {
      if (e instanceof StopRequested) throw e;
      log(`    [i] Post-step failed (${e?.name || 'Error'}) — skipped, account kept.`);
    }
  }

  return { ok: true, birthday: birthdayOut };
}
